
CREATE TABLE OT.USUARIOS (
  ID_USUARIO NUMBER DEFAULT OT.USUARIOS_ID_USUARIO_SEQ.NEXTVAL PRIMARY KEY,
  NOMBRE_USUARIO VARCHAR2(80 BYTE) NOT NULL,
  APELLIDO_PATERNO VARCHAR2(80 BYTE) NOT NULL,
  APELLIDO_MATERNO VARCHAR2(80 BYTE) NOT NULL,
  CORREO_USUARIO VARCHAR2(80 BYTE) NOT NULL,
  PASSWORD_USUARIO VARCHAR2(80 BYTE) NOT NULL,
  ROL_USUARIO VARCHAR2(211 BYTE) NOT NULL,
  CHECK (ROL_USUARIO IN ('Administrador', 'Operador'))
);

CREATE TABLE OT.SEG_AUTHORITY (
  AUTHORITY_ID NUMBER DEFAULT OT.SEG_AUTHORITY_AUTHORITY_ID_SEQ.NEXTVAL PRIMARY KEY,
  NAME VARCHAR2(255 BYTE)
);

CREATE TABLE OT.SEG_USER_AUTHORITY (
  USER_ID NUMBER NOT NULL,
  AUTHORITY_ID NUMBER NOT NULL,
  PRIMARY KEY (USER_ID, AUTHORITY_ID),
  CONSTRAINT FK_USER_AUTHORITY_AUTHORITY FOREIGN KEY (AUTHORITY_ID)
    REFERENCES OT.SEG_AUTHORITY (AUTHORITY_ID),
  CONSTRAINT FK_USER_AUTHORITY_USER FOREIGN KEY (USER_ID)
    REFERENCES OT.SEG_USER (USER_ID)
);

CREATE TABLE OT.FACTURA (
  ID_FOLIO NUMBER DEFAULT OT.FACTURA_ID_FOLIO_SEQ.NEXTVAL PRIMARY KEY,
  FOLIO NUMBER NOT NULL,
  STATUS VARCHAR2(35 BYTE) NOT NULL,
  CASO_REPORTADO VARCHAR2(50 BYTE) NOT NULL,
  CATEGORIA_SOLUCION VARCHAR2(50 BYTE) NOT NULL,
  CATEGORIA_PROBLEMA VARCHAR2(50 BYTE) NOT NULL,
  CORREO_CLIENTE VARCHAR2(50 BYTE) NOT NULL,
  NUMERO_FACTURA NUMBER NOT NULL,
  FOLIO_VENTA VARCHAR2(50 BYTE) NOT NULL,
  CATEGORIA_FACTURACION VARCHAR2(50 BYTE) NOT NULL,
  FECHA_RECEPCION DATE DEFAULT SYSDATE NOT NULL,
  FECHA_PRIMER_ATENCION DATE,
  FECHA_SOLUCION DATE,
  FECHA_CIERRE DATE,
  REGISTRO_ACTIVO NUMBER DEFAULT 1 NOT NULL,
  CHECK (STATUS IN ('Abierto', 'Solucionado', 'Caso_Cerrado'))
);

CREATE TABLE OT.TICKET_PLAZA (
  ID_TICKET NUMBER DEFAULT OT.TICKET_PLAZA_ID_TICKET_SEQ.NEXTVAL NOT NULL,
  FOLIO_VENTA NUMBER NOT NULL,
  PLAZA VARCHAR2(50 BYTE) NOT NULL,
  TIENDA VARCHAR2(35 BYTE) NOT NULL,
  STATUS VARCHAR2(35 BYTE) NOT NULL,
  ENTIDAD VARCHAR2(35 BYTE) NOT NULL,
  FECHA DATE DEFAULT SYSDATE NOT NULL,
  SUBTOTAL_VENTA NUMBER(10,2) NOT NULL,
  TOTAL_VENTA NUMBER(10,2) NOT NULL,
  CAJA NUMBER(5,0) NOT NULL,
  NUM_TICKET NUMBER NOT NULL,
  REGISTRO_ACTIVO NUMBER DEFAULT 1 NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  CONSTRAINT TICKET_PLAZA_PK PRIMARY KEY (ID_TICKET),
  CONSTRAINT FK_TICKET_PLAZA_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES OT.USUARIOS (ID_USUARIO)
);

CREATE TABLE OT.INCIDENTE (
  ID_INCIDENTE NUMBER DEFAULT OT.INCIDENTE_ID_INCIDENTE_SEQ.NEXTVAL NOT NULL,
  NOMBRE_INCIDENTE VARCHAR2(35 BYTE) NOT NULL,
  DESCRIPCION_INCIDENTE VARCHAR2(60 BYTE) NOT NULL,
  FECHA_INCIDENTE DATE DEFAULT SYSDATE NOT NULL,
  DIRECCION_IMAGEN_INCIDENTE VARCHAR2(100 BYTE) NOT NULL,
  STATUS VARCHAR2(35 BYTE) NOT NULL CHECK (STATUS IN ('Liberado', 'Espera')),
  IMPACTO VARCHAR2(35 BYTE) NOT NULL,
  URGENCIA VARCHAR2(35 BYTE) NOT NULL,
  PRIORIDAD VARCHAR2(35 BYTE) NOT NULL CHECK (PRIORIDAD IN ('Baja', 'Media', 'Alta', 'Otra')),
  PRIORIDAD_EXTRA VARCHAR2(35 BYTE),
  REGISTRO_ACTIVO NUMBER DEFAULT 1 NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  CONSTRAINT INCIDENTE_PK PRIMARY KEY (ID_INCIDENTE),
  CONSTRAINT FK_INCIDENTE_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES OT.USUARIOS (ID_USUARIO)
);

CREATE TABLE OT.REPORTE_TICKET (
  ID_REPORTE NUMBER DEFAULT OT.REPORTE_TICKET_ID_REPORTE_SEQ.NEXTVAL NOT NULL,
  NOMBRE_REPORTE VARCHAR2(35 BYTE) NOT NULL,
  DESCRIPCION VARCHAR2(60 BYTE) NOT NULL,
  FECHA DATE NOT NULL,
  STATUS VARCHAR2(35 BYTE) NOT NULL CHECK (STATUS IN ('Liberado', 'Espera')),
  PLAZA VARCHAR2(35 BYTE) NOT NULL,
  TIENDA VARCHAR2(35 BYTE) NOT NULL,
  REGISTRO_ACTIVO NUMBER DEFAULT 1 NOT NULL,
  ID_TICKET NUMBER NOT NULL,
  PRIMARY KEY (ID_REPORTE),
  CONSTRAINT FK_REPORTE_TICKET_TICKET FOREIGN KEY (ID_TICKET)
    REFERENCES OT.TICKET_PLAZA (ID_TICKET)
);
